import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="flex flex-col min-h-screen">
          <header className="sticky top-0 bg-white shadow-md z-10">
            <div className="flex items-center justify-between max-w-7xl mx-auto">
              <div className="flex items-center">
                {/* brand image */}
                <div className="h-8 w-8 bg-gray-200 rounded"></div>
              </div>
              <nav>
                <ul className="flex space-x-4">
                  <li className="hover:underline cursor-pointer">Link 1</li>
                  <li className="hover:underline cursor-pointer">Link 2</li>
                  <li className="hover:underline cursor-pointer">Link 3</li>
                </ul>
              </nav>
            </div>
          </header>

          <main className="flex-grow flex justify-center items-start mt-8">
            <div className="w-full px-10">{children}</div>
          </main>

          <footer className="sticky bottom-0 bg-gray-100 shadow-inner">
            <div className="text-center py-2">© 2025 Your App</div>
          </footer>
        </div>
      </body>
    </html>
  );
}
